package com.alphasystem.primereact.icons

import enumeratum.EnumEntry.Hyphencase
import enumeratum.{ CirceEnum, Enum, EnumEntry }

sealed trait Icon extends EnumEntry with Hyphencase {
  val toClassName: String = s"pi pi-$entryName"
}

case object Icon extends Enum[Icon] with CirceEnum[Icon] {
  override def values: IndexedSeq[Icon] = findValues

  final case object AlignCenter extends Icon
  final case object AlignJustify extends Icon
  final case object AlignLeft extends Icon
  final case object AlignRight extends Icon
  final case object Amazon extends Icon
  final case object Android extends Icon
  final case object AngleDoubleDown extends Icon
  final case object AngleDoubleLeft extends Icon
  final case object AngleDoubleRight extends Icon
  final case object AngleDoubleUp extends Icon
  final case object AngleDown extends Icon
  final case object AngleLeft extends Icon
  final case object AngleRight extends Icon
  final case object AngleUp extends Icon
  final case object Apple extends Icon
  final case object ArrowCircleDown extends Icon
  final case object ArrowCircleLeft extends Icon
  final case object ArrowCircleRight extends Icon
  final case object ArrowCircleUp extends Icon
  final case object ArrowDown extends Icon
  final case object ArrowLeft extends Icon
  final case object ArrowRight extends Icon
  final case object ArrowUp extends Icon
  final case object Backward extends Icon
  final case object Ban extends Icon
  final case object Bars extends Icon
  final case object Bell extends Icon
  final case object Book extends Icon
  final case object Bookmark extends Icon
  final case object Briefcase extends Icon
  final case object Calendar extends Icon
  final case object CalendarMinus extends Icon
  final case object CalendarPlus extends Icon
  final case object CalendarTimes extends Icon
  final case object Camera extends Icon
  final case object CaretDown extends Icon
  final case object CaretLeft extends Icon
  final case object CaretRight extends Icon
  final case object CaretUp extends Icon
  final case object ChartBar extends Icon
  final case object ChartLine extends Icon
  final case object Check extends Icon
  final case object CheckCircle extends Icon
  final case object CheckSquare extends Icon
  final case object ChevronCircleDown extends Icon
  final case object ChevronCircleLeft extends Icon
  final case object ChevronCircleRight extends Icon
  final case object ChevronCircleUp extends Icon
  final case object ChevronDown extends Icon
  final case object ChevronLeft extends Icon
  final case object ChevronRight extends Icon
  final case object ChevronUp extends Icon
  final case object CircleOff extends Icon
  final case object CircleOn extends Icon
  final case object Clock extends Icon
  final case object Clone extends Icon
  final case object Cloud extends Icon
  final case object CloudDownload extends Icon
  final case object CloudUpload extends Icon
  final case object Cog extends Icon
  final case object Comment extends Icon
  final case object Comments extends Icon
  final case object Compass extends Icon
  final case object Copy extends Icon
  final case object CreditCard extends Icon
  final case object Desktop extends Icon
  final case object Directions extends Icon
  final case object DirectionsAlt extends Icon
  final case object Discord extends Icon
  final case object Dollar extends Icon
  final case object Download extends Icon
  final case object Eject extends Icon
  final case object EllipsisH extends Icon
  final case object EllipsisV extends Icon
  final case object Envelope extends Icon
  final case object Euro extends Icon
  final case object ExclamationCircle extends Icon
  final case object ExclamationTriangle extends Icon
  final case object ExternalLink extends Icon
  final case object Eye extends Icon
  final case object EyeSlash extends Icon
  final case object Facebook extends Icon
  final case object FastBackward extends Icon
  final case object FastForward extends Icon
  final case object File extends Icon
  final case object FileExcel extends Icon
  final case object FileO extends Icon
  final case object FilePdf extends Icon
  final case object Filter extends Icon
  final case object FilterSlash extends Icon
  final case object Flag extends Icon
  final case object Folder extends Icon
  final case object FolderOpen extends Icon
  final case object Forward extends Icon
  final case object Github extends Icon
  final case object Globe extends Icon
  final case object Google extends Icon
  final case object Heart extends Icon
  final case object Home extends Icon
  final case object IdCard extends Icon
  final case object Image extends Icon
  final case object Images extends Icon
  final case object Inbox extends Icon
  final case object Info extends Icon
  final case object InfoCircle extends Icon
  final case object Key extends Icon
  final case object Link extends Icon
  final case object List extends Icon
  final case object Lock extends Icon
  final case object LockOpen extends Icon
  final case object Map extends Icon
  final case object MapMarker extends Icon
  final case object Microsoft extends Icon
  final case object Minus extends Icon
  final case object MinusCircle extends Icon
  final case object Mobile extends Icon
  final case object MoneyBill extends Icon
  final case object Moon extends Icon
  final case object Palette extends Icon
  final case object Paperclip extends Icon
  final case object Pause extends Icon
  final case object Paypal extends Icon
  final case object Pencil extends Icon
  final case object Percentage extends Icon
  final case object Phone extends Icon
  final case object Play extends Icon
  final case object Plus extends Icon
  final case object PlusCircle extends Icon
  final case object PowerOff extends Icon
  final case object Print extends Icon
  final case object Question extends Icon
  final case object QuestionCircle extends Icon
  final case object Refresh extends Icon
  final case object Replay extends Icon
  final case object Reply extends Icon
  final case object Save extends Icon
  final case object Search extends Icon
  final case object SearchMinus extends Icon
  final case object SearchPlus extends Icon
  final case object Send extends Icon
  final case object ShareAlt extends Icon
  final case object Shield extends Icon
  final case object ShoppingCart extends Icon
  final case object SignIn extends Icon
  final case object SignOut extends Icon
  final case object Sitemap extends Icon
  final case object Slack extends Icon
  final case object SlidersH extends Icon
  final case object SlidersV extends Icon
  final case object Sort extends Icon
  final case object SortAlphaDown extends Icon
  final case object SortAlphaDownAlt extends Icon
  final case object SortAlphaUp extends Icon
  final case object SortAlphaUpAlt extends Icon
  final case object SortAlt extends Icon
  final case object SortAmountDown extends Icon
  final case object SortAmountDownAlt extends Icon
  final case object SortAmountUp extends Icon
  final case object SortAmountUpAlt extends Icon
  final case object SortDown extends Icon
  final case object SortNumericDown extends Icon
  final case object SortNumericDownAlt extends Icon
  final case object SortNumericUp extends Icon
  final case object SortNumericUpAlt extends Icon
  final case object SortUp extends Icon
  final case object Spinner extends Icon
  final case object Star extends Icon
  final case object StarO extends Icon
  final case object StepBackward extends Icon
  final case object StepBackwardAlt extends Icon
  final case object StepForward extends Icon
  final case object StepForwardAlt extends Icon
  final case object Sun extends Icon
  final case object Table extends Icon
  final case object Tablet extends Icon
  final case object Tag extends Icon
  final case object Tags extends Icon
  final case object ThLarge extends Icon
  final case object ThumbsDown extends Icon
  final case object ThumbsUp extends Icon
  final case object Ticket extends Icon
  final case object Times extends Icon
  final case object TimesCircle extends Icon
  final case object Trash extends Icon
  final case object Twitter extends Icon
  final case object Undo extends Icon
  final case object Unlock extends Icon
  final case object Upload extends Icon
  final case object User extends Icon
  final case object UserEdit extends Icon
  final case object UserMinus extends Icon
  final case object UserPlus extends Icon
  final case object Users extends Icon
  final case object Video extends Icon
  final case object Vimeo extends Icon
  final case object VolumeDown extends Icon
  final case object VolumeOff extends Icon
  final case object VolumeUp extends Icon
  final case object Wallet extends Icon
  final case object Wifi extends Icon
  final case object WindowMaximize extends Icon
  final case object WindowMinimize extends Icon
  final case object Youtube extends Icon
}
